// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJxOUX_2vegbJ9No-wznJwqo5qIVJu-Ks',
    appId: '1:245953274379:web:64dd1f8cc573298c271d0e',
    messagingSenderId: '245953274379',
    projectId: 'recipe-finder-meal-planner',
    authDomain: 'recipe-finder-meal-planner.firebaseapp.com',
    storageBucket: 'recipe-finder-meal-planner.firebasestorage.app',
    measurementId: 'G-ZJKKH44VWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE2QycEWzo86FHBxvb6TApUCLacrKE-Zc',
    appId: '1:245953274379:android:1f0726a5e8ff0969271d0e',
    messagingSenderId: '245953274379',
    projectId: 'recipe-finder-meal-planner',
    storageBucket: 'recipe-finder-meal-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpL0AQ0GnAVF3W4oyqCvT-Yu33AZDZGqA',
    appId: '1:245953274379:ios:f2f22958588cc7aa271d0e',
    messagingSenderId: '245953274379',
    projectId: 'recipe-finder-meal-planner',
    storageBucket: 'recipe-finder-meal-planner.firebasestorage.app',
    iosBundleId: 'com.example.recipeFinderMealPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpL0AQ0GnAVF3W4oyqCvT-Yu33AZDZGqA',
    appId: '1:245953274379:ios:f2f22958588cc7aa271d0e',
    messagingSenderId: '245953274379',
    projectId: 'recipe-finder-meal-planner',
    storageBucket: 'recipe-finder-meal-planner.firebasestorage.app',
    iosBundleId: 'com.example.recipeFinderMealPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJxOUX_2vegbJ9No-wznJwqo5qIVJu-Ks',
    appId: '1:245953274379:web:10a15688dc675d64271d0e',
    messagingSenderId: '245953274379',
    projectId: 'recipe-finder-meal-planner',
    authDomain: 'recipe-finder-meal-planner.firebaseapp.com',
    storageBucket: 'recipe-finder-meal-planner.firebasestorage.app',
    measurementId: 'G-J1K1DGJFED',
  );
}
